### PR TITLE
Added userContainerColor , other ContainerColor and showPointedMessag…

### PR DESCRIPTION
**Pull request by sijangurung**
- userContainerColor - to change the color for current user message container
- otherContainerColor - to change the color of others message container
- showPointedMessageContainer ( bool ) - to show pointed message container

### CODE REVIEW

**Comment by fayeed** [comment]
@sijangurung How does `useContainerColor` & `otherContainerColor` differ from ChatUser's `containerColor` property?

**Comment by sijangurung** [comment]
if you want to have a generic color fo all the container ( for user and other ) , instead of assigning it to every user object . As per a common usecase, The user object will directly from from Database where you will not manipulate the user-object ,just to add a color. 
The color of the Container, is more of a Widgets style property , rather than users property. 
Thanks for the question !

**Comment by fayeed** [comment]
@sijangurung I think would be better to have a `messageDecorationBuilder` as mentioned in issue #85 then have an individual property for colors & showing pointed edges, the reason is you have set the edges for the bottom so what if someone wants to set it to top edges or what if someone wants to change something else so adding a new property for everything is not feasible. 

The `messageDecorationBuilder` would probably be a function like so:
```dart
BoxDecoration messageDecorationBuilder(message: ChatMessage, isUser: boolean);
```

If you have any questions regarding this let me know.

**Comment by sijangurung** [comment]
show messageDecorationBuilder has high priority above messageContainerDecoration , meaning in message_container.dart
`child: Container(
        decoration: messageContainerDecoration != null
            ? messageContainerDecoration.copyWith(
                color: message.user.containerColor != null
                    ? message.user.containerColor
                    : messageContainerDecoration.color,
              )
            : messageDecorationBuilder != null
                ? messageDecorationBuilder(message, isUser)
                : BoxDecoration(
                    color: message.user.containerColor != null
                        ? message.user.containerColor
                        : isUser
                            ? Theme.of(context).accentColor
                            : Color.fromRGBO(225, 225, 225, 1),
                    borderRadius: BorderRadius.circular(5.0),
                  ),`
or 
`child: Container(
        decoration: messageDecorationBuilder != null
           ? messageDecorationBuilder(message, isUser)
            : messageDecorationBuilder != null 
                  ? messageContainerDecoration.copyWith(
                   color: message.user.containerColor != null
                         ? message.user.containerColor
                         : messageContainerDecoration.color,
                   )
                : BoxDecoration(
                    color: message.user.containerColor != null
                        ? message.user.containerColor
                        : isUser
                            ? Theme.of(context).accentColor
                            : Color.fromRGBO(225, 225, 225, 1),
                    borderRadius: BorderRadius.circular(5.0),
                  ),`

**Comment by fayeed** [comment]
Yeah, `messageDecorationBuilder` should have a higher priority than `messageContainerDecoration`.

**Comment by sijangurung** [comment]
Okay , i will open new PR for messageDecorationBuilder, so you can close it after i do that ! Thanks for the reply 
@fayeed

**Pull request closed without merging**
