### PR TITLE
Added flag shouldStartMessagesFromTop to allow users to start message…

### PR DESCRIPTION
**Pull request by ngoctranfire**
Here's the behavior when the flag is set to align to the top:
Screen Shot 2020-05-12 at 11 19 37 PM

Here's a behavior when the flag is set to align to the bottom:
Screen Shot 2020-05-12 at 11 20 07 PM

I think this is a good to have because sometimes, when the chat isn't filled, we should show from the top (as we can then show other views and interactions on top of it).

### CODE REVIEW

**Comment by ngoctranfire** [comment]
@fayeed Would love a review for this whenever you can!

**Comment by ngoctranfire** [comment]
This would also close issue #79 that I referenced.

**Comment by SebastienBtr** [comment]
I understand your use case, it seems very specific and I never seen that in a chat app, maybe an other solution, that requires nothing new, is to use the `messageContainerPadding` property to add a padding bottom to the chat_view when you need it, so your buttons doesn't hide the message.

**Comment by ngoctranfire** [comment]
@SebastienBtr, I tried and considered that, but then I don't actually know the height or how much padding I will need (and having a huge padding for the messages can be a little bit weird). There are cases where I think this can be useful (I think more so in a read-only format where there is only a few messages).

**Comment by fayeed** [comment]
@SebastienBtr Yeah I think this is really specific but then again there are few use cases where you might want to replicate this behavior. As this package is all about customizability I this should be included.

**Comment by fayeed** [comment]
@ngoctranfire Can you fix the conflicts & also update the README.md with the new property.

**Comment by ngoctranfire** [comment]
@fayeed Done! Please review and verify things look good!

**Comment by fayeed** [comment]
@ngoctranfire Thanks for the PR.

**Comment by SubashManian** [comment]
@fayeed  @ngoctranfire  did you tested with the input text field in the below. If i apply this i'm getting like this did you faced this issue from your side. Any solution for this.

Thanks
IMG_0060

**Pull request merged**
