### PR TITLE
Wrap `ChatInputToolbar` in a `SafeArea` widget

### PR DESCRIPTION
**Pull request by prufect**

### CODE REVIEW

**Comment by SebastienBtr** [comment]
Thanks,  I think that was indeed missing!

**Comment by prufect** [comment]
Hey no worries, will you be merging this in?

**Comment by SebastienBtr** [comment]
@fayeed ?

**Comment by fayeed** [comment]
@prufect thanks for the PR.

**Comment by aytunch** [comment]
I think this PR should be reverted. This package should not add a `SafeArea` into  the input widget. We should do it in our apps if necessary. 
@fayeed I know you are not maintaining this anymore. How should I revert it and use it in our app? Also will you continue working on v2? Some screenshots would be very helpful for the new package

**Pull request merged**
