### PR TITLE
Add inputDisabled

### PR DESCRIPTION
**Pull request by SiDevesh**
* Update chat_view.dart

* Update chat_input_toolbar.dart

* Update README.md

### CODE REVIEW

**Comment by SebastienBtr** [comment]
Hi, thanks for your PR, can you add more context? There is already a `readOnly` parameter (apparently it is not in the readme, sorry for that)

**Comment by fayeed** [comment]
@SebastienBtr `readOnly` parameter is for hiding the input completely, it was added to provide a way to have guided conversation using quick replies and this PR just seems to add a way to disable the input.

**Comment by SebastienBtr** [comment]
Yeah I guess that fine then, just wanted to be sure it was not redundant. The `readOnly` param needs to be added to the readme though.

**Comment by fayeed** [comment]
@SebastienBtr Yeah sure, I will add it when I will update the package.

**Comment by fayeed** [comment]
@SiDevesh Thanks for the PR.

**Pull request merged**
