### PR TITLE
using WidgetsBinding.instance.addPostFrameCallback to prevent loading…

### LINKED ISSUE #35: Scroll to last index
The current implementation displays the first message then jumps to the last message. This breaks the user's focus and seems buggy but it's not. How can I prevent this and always show the latest messages. I've done this in a custom chat app but this plugin saves a lot of time.

check out the unwanted behavior here: https://1drv.ms/v/s!AqyIwuPueLgbq36o4gxQSomsZy3o?e=9HmIFr

### PR DESCRIPTION
**Pull request by Dreamersoul**
… the widget from looking jittery closes #35

### CODE REVIEW

**Comment by fayeed** [comment]
@Dreamersoul Thanks for the PR, can you resolve the merge conflict I will then merge and update the package.

**Comment by Dreamersoul** [comment]
You're welcome, will do in a few hours 👍🏼

**Comment by Dreamersoul** [comment]
fixed conflict

**Comment by fayeed** [comment]
@Dreamersoul Thanks for the PR I have merged the changes, and will soon upload the new version.

**Pull request merged**
