### PR TITLE
fix scroll to top when inverted and send closes #48

### LINKED ISSUE #48: On inverse and sending a message the list scrolls to the top
as described and shown in the discussion #35 im assuming the issue is from this line https://github.com/fayeed/dash_chat/blob/master/lib/src/chat_view.dart#L386 , will try to implement a fix soon

### PR DESCRIPTION
**Pull request by Dreamersoul**

### CODE REVIEW

**Comment by Dreamersoul** [comment]
Any update?

**Comment by fayeed** [comment]
@Dreamersoul sorry for the late response I totally forgot about your PR, there are some formatting issues that can you fix them.

**Comment by Dreamersoul** [comment]
fixed can you take a look?

**Comment by fayeed** [comment]
@Dreamersoul Thanks for the PR.

**Pull request merged**
